version: 2
jobs:
  build:
    docker:
      - image: saltyrtc/circleci-image-rs:latest
    steps:
      - checkout
      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ checksum "Cargo.lock" }}
            - v1-cargo-cache-{{ .Branch }}
            - v1-cargo-cache
      - run: cargo build && cargo test
      - run: cargo install --force cargo-audit && cargo audit
      - save_cache:
          key: v1-cargo-cache-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v1-cargo-cache-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v1-cargo-cache
          paths:
            - target
            - /usr/local/cargo
